### ISSUE TITLE
Possible reason why Windows CI failing after PR #19

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-build-system#20]
When I try to run the `build_nim.sh` on Windows, the result is a file `nim` without `.exe` among other files.
This `nim` file can be executed by `msys bash` but not with other terminal.
But this is probably the problem because it is the only visible difference compared to older version.

**Comment by stefantalpalaru** [comment]
Fixed.

Thanks for the debugging. That's exactly what was happening.
