### ISSUE TITLE
wrong commit checked out in vendor/Nim after make update

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nimbus-build-system#21]
Locally I bumped a repo that uses nimbus-build-system to use the latest commit on this repo's `master`.

After `make update` (or even a nuke: `git clean -dfx && rm -rf vendor/* && make -j16 update`) the commit on `vendor/nimbus-build-system/vendor/Nim` seems to be incorrect. It's at [`bf320ed172f74f60fd274338e82bdc9ce3520dd9`](https://github.com/status-im/Nim/tree/bf320ed172f74f60fd274338e82bdc9ce3520dd9) when it should be at [`121628357ec7fae91335bd392f03b0e6dd249319`](121628357ec7fae91335bd392f03b0e6dd249319).

If I `cd vendor/nimbus-build-system && git submodule update` then it changes to the correct commit but that shouldn't be necessary, right?

**Comment by michaelsbradleyjr** [comment]
I tried `rm -rf .git/modules` and then re-nuked and the problem went away, not sure what had gone wrong but I remembered one other time last year when I had to do that.

**Comment by stefantalpalaru** [comment]
Before running `make update`, make sure you add and commit the top-level repo changes.

Any uncommitted submodule bump will be wiped out, because that's how submodule updating works.

**Comment by michaelsbradleyjr** [comment]
> Before running `make update`, make sure you add and commit the top-level repo changes.
> 
> Any uncommitted submodule bump will be wiped out, because that's how submodule updating works.

I had. Something got messed up in `.git/modules` somehow, and I needed to wipe it. I've very rarely run into this situation, so it's hard to speculate re: the cause.

**Comment by michaelsbradleyjr** [comment]
I fired up my Linux laptop, checked out the branch I was working on earlier (on macOS laptop), nuked it (see above), and ran into the same problem.

The symptom is that the top-level repo reports that submodule `vendor/nimbus-build-system` is dirty. When I `cd vendor/nimbus-build-system && git status` I get:
```
Changes not stage for commit:
  ...
        modified:    vendor/Nim (new commits)
```

Comparing to what I wrote above in the PR description, it's the exact same situation re: the outdated commit in `vendor/nimbus-build-system/vendor/Nim`.

Re-opening this issue.

**Comment by stefantalpalaru** [comment]
Don't delete internal directories.

Any message from `make update`?

**Comment by michaelsbradleyjr** [comment]
> Don't delete internal directories.
> 
> Any message from `make update`?

None whatsoever, `make update` reported all is well.

**Comment by stefantalpalaru** [comment]
Try `make V=1 update`

**Comment by michaelsbradleyjr** [comment]
Already did, no effect.

Then I did `cd vendor/nimbus-build-system && git submodule update`. At that point the submodule has the correct commit. But, weirdly, if I go back to the top-level of the repo and do `make V=1 update` (have been leaving out the `V=1` in my description and comments here, but I always do that), I'm back to the `modified: vendor/Nim (new commits)`  situation. Nothing strange that I noticed is ever reported by `make V=1 update`.

**Comment by stefantalpalaru** [comment]
I remember seeing multiple instances of nimbus-build-system as a Git submodule in one of the Status projects, due to a submodule using it. Could that be your case?

**Comment by michaelsbradleyjr** [comment]
I'm not sure, but this just finished:
```
rm -rf .git/modules && git clean -dfx && rm -rf vendor/* && make V=1 update
```
After that, it's clean again, no more `modified: vendor/Nim (new commits)`.

**Comment by michaelsbradleyjr** [comment]
In the top-level `.gitmodules` there's only one listing for `nimbus-build-system` and the same is true for `.git/config`.

I checked some commits back in the repo, and that's also the case.

**Comment by stefantalpalaru** [comment]
You wouldn't find it there. Run `find -type d -name nimbus-build-system`

nim-status-client, for example, has it both in "vendor/nimbus-build-system" and in "vendor/nim-status/vendor/nimbus-build-system"

**Comment by michaelsbradleyjr** [comment]
I'm working in the `status-im/nim-status` repo on the `feat/examples/client` branch:
```
$ find . -type d | grep nimbus-build-system
```
After getting rid of the noise:
```
./nim-waku/vendor/nimbus-build-system
./nim-task-runner/vendor/nimbus-build-system
./nim-sqlcipher/vendor/nimbus-build-system
./nimbus-build-system
```
