### ISSUE TITLE
USE_SYSTEM_NIM doesn't work in nim-waku.

### ISSUE THREAD

**Issue by sbc64** [status-im/nimbus-build-system#22]
I'm trying to build https://github.com/status-im/nim-waku using https://github.com/NixOS/nixpkgs. One of the peculiarities of nix is that I don't have access to the internet during the build process. It is basically sandboxed and I need to to pre define the dependencies before the build starts.

I've tried to replicate all of the steps of the `make wakunode2` rule in nim-waku repo. This rule depends on the `deps-common` rule of this reposity which downloads the nim-binary. I don't want the `make wakunode2` rule to download the nim binary so I try to run it with USE_SYSTEM_NIM=1 environment variable. The goal is that with nix I will be providing the nim binary path.

It seems to me that the USE_SYSTEM_NIM variable is not doing what is supposed to do and the Makefile still tries to executes the `$(NIM_BINARY) `rule defined here https://github.com/status-im/nimbus-build-system/blob/master/makefiles/targets.mk#L61,#L62.

A quick demonstration of this can be seen with this command:

```bash
nim-waku on  master on ☁️  eu-central-1
➜ USE_SYSTEM_NIM=1 make wakunode2

Tip of the day: this will probably build faster if you use "make -j8 ...".

Building: Nim compiler
^Cmake[1]: *** [vendor/nimbus-build-system/makefiles/targets.mk:75: build-nim] Interrupt
make: *** [vendor/nimbus-build-system/makefiles/targets.mk:106: vendor/nimbus-build-system/vendor/Nim/bin/nim] Interrupt
```

I tried changing the line to something like this:

```make
deps-common: | sanity-checks warn-update warn-jobs $(NIMBLE_DIR)
 # - don't build our Nim target if it's not going to be used
ifeq ($(USE_SYSTEM_NIM), 0)
   $(MAKE) $(NIM_BINARY)
endif
```
But it seems that no matter what I do the USE_SYSTEM_NIM variable is set to 0 from the `variables.mk` file.

My work around so far is to change it with `sed`

`sed -i 's/USE_SYSTEM_NIM := 0/USE_SYSTEM_NIM := 1/g' vendor/nimbus-build-system/makefiles/variables.mk`

Thanks for reading!

**Comment by stefantalpalaru** [comment]
> USE_SYSTEM_NIM=1 environment variable

It doesn't work as an environment variable. You need to pass it on the MAKE command line, as a parameter, as described here: https://github.com/status-im/nimbus-build-system#use_system_nim

**Comment by sbc64** [comment]
That seems to do the trick. Sorry for the disturbance.

in case this helps anyone to avoid my mistake, this is the wrong way:

`USE_SYSTEM_NIM=1 make wakunode2`

the correct way is

`make USE_SYSTEM_NIM=1 wakunode2`
