### ISSUE TITLE
variable to allow current project to be imported unprefixed

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nimbus-build-system#24]
Many Nim repos in the status-im GitHub org (and many Nim repos in general) follow this pattern:
* The repo is `nim-foo` implementing a Nim library that will be imported as `foo`.
* In the root of repo there is `foo.nim` and a `foo/` dir containing modules that implement the lib.

The nimbus-build-system allows for `vendor/` dependencies to be `import`ed as if they were conventionally installed nimble deps.

Could nimbus-build-system / `env.sh` allow for passing a variable such that modules under an `examples/` directory (or `test/`, etc.) in the root of the repo could `import foo` or `import foo/bar/baz` as if `foo` was also a conventionally installed nimble dep? That is, as opposed to `examples/a/b/c.nim` doing `import ../../../foo` or `import ../../../foo/bar/baz`.

**Comment by stefantalpalaru** [comment]
It's easier to specify a relative path in a local config file:

```text
vendor/nim-normalize/tests/nim.cfg:1:--path:"../src/"
vendor/nim-unittest2/tests/nim.cfg:1:--path:"$projectDir/.."
vendor/nim-chronicles/nim.cfg:1:--path: "."
vendor/nim-testutils/ntu.nim.cfg:2:--path="$config"
vendor/nim-unicodedb/tests/nim.cfg:1:--path:"../src/"
vendor/karax/examples/scrollapp/scrollapp.nims:1:--path: "../.."
vendor/karax/examples/todoapp/todoapp.nims:1:--path: "../.."
vendor/karax/examples/carousel/carousel.nims:1:--path: "../../karax"
vendor/karax/examples/mediaplayer/playerapp.nims:1:--path: "../.."
vendor/karax/tests/nim.cfg:1:--path: "../karax"
vendor/karax/experiments/refs/demo.nims:1:--path: "../../src"
```

**Comment by michaelsbradleyjr** [comment]
> It's easier to specify a relative path in a local config file:

Awesome, thank you. TIL.

**Comment by michaelsbradleyjr** [comment]
See: https://github.com/status-im/nim-status/pull/262
